# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import access_point_pb2 as access__point__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in access_point_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccessPointServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/tiedie.ap.AccessPointService/Health',
                request_serializer=access__point__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=access__point__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Connect = channel.unary_unary(
                '/tiedie.ap.AccessPointService/Connect',
                request_serializer=access__point__pb2.ConnectRequest.SerializeToString,
                response_deserializer=access__point__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.Discover = channel.unary_unary(
                '/tiedie.ap.AccessPointService/Discover',
                request_serializer=access__point__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=access__point__pb2.DiscoverResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/tiedie.ap.AccessPointService/Read',
                request_serializer=access__point__pb2.ReadRequest.SerializeToString,
                response_deserializer=access__point__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/tiedie.ap.AccessPointService/Write',
                request_serializer=access__point__pb2.WriteRequest.SerializeToString,
                response_deserializer=access__point__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/tiedie.ap.AccessPointService/Disconnect',
                request_serializer=access__point__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=access__point__pb2.DisconnectResponse.FromString,
                _registered_method=True)
        self.StreamAdvertisements = channel.unary_stream(
                '/tiedie.ap.AccessPointService/StreamAdvertisements',
                request_serializer=access__point__pb2.AdvertisementStreamRequest.SerializeToString,
                response_deserializer=access__point__pb2.AdvertisementBatch.FromString,
                _registered_method=True)
        self.StreamConnectionEvents = channel.unary_stream(
                '/tiedie.ap.AccessPointService/StreamConnectionEvents',
                request_serializer=access__point__pb2.ConnectionStreamRequest.SerializeToString,
                response_deserializer=access__point__pb2.ConnectionEvent.FromString,
                _registered_method=True)


class AccessPointServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Discover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAdvertisements(self, request, context):
        """Server stream of advertisement events from an AP.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamConnectionEvents(self, request, context):
        """Server stream of connection events from an AP.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccessPointServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=access__point__pb2.HealthCheckRequest.FromString,
                    response_serializer=access__point__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=access__point__pb2.ConnectRequest.FromString,
                    response_serializer=access__point__pb2.ConnectResponse.SerializeToString,
            ),
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=access__point__pb2.DiscoverRequest.FromString,
                    response_serializer=access__point__pb2.DiscoverResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=access__point__pb2.ReadRequest.FromString,
                    response_serializer=access__point__pb2.ReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=access__point__pb2.WriteRequest.FromString,
                    response_serializer=access__point__pb2.WriteResponse.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=access__point__pb2.DisconnectRequest.FromString,
                    response_serializer=access__point__pb2.DisconnectResponse.SerializeToString,
            ),
            'StreamAdvertisements': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAdvertisements,
                    request_deserializer=access__point__pb2.AdvertisementStreamRequest.FromString,
                    response_serializer=access__point__pb2.AdvertisementBatch.SerializeToString,
            ),
            'StreamConnectionEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamConnectionEvents,
                    request_deserializer=access__point__pb2.ConnectionStreamRequest.FromString,
                    response_serializer=access__point__pb2.ConnectionEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tiedie.ap.AccessPointService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tiedie.ap.AccessPointService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccessPointService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tiedie.ap.AccessPointService/Health',
            access__point__pb2.HealthCheckRequest.SerializeToString,
            access__point__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tiedie.ap.AccessPointService/Connect',
            access__point__pb2.ConnectRequest.SerializeToString,
            access__point__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tiedie.ap.AccessPointService/Discover',
            access__point__pb2.DiscoverRequest.SerializeToString,
            access__point__pb2.DiscoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tiedie.ap.AccessPointService/Read',
            access__point__pb2.ReadRequest.SerializeToString,
            access__point__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tiedie.ap.AccessPointService/Write',
            access__point__pb2.WriteRequest.SerializeToString,
            access__point__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tiedie.ap.AccessPointService/Disconnect',
            access__point__pb2.DisconnectRequest.SerializeToString,
            access__point__pb2.DisconnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAdvertisements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tiedie.ap.AccessPointService/StreamAdvertisements',
            access__point__pb2.AdvertisementStreamRequest.SerializeToString,
            access__point__pb2.AdvertisementBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamConnectionEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tiedie.ap.AccessPointService/StreamConnectionEvents',
            access__point__pb2.ConnectionStreamRequest.SerializeToString,
            access__point__pb2.ConnectionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
